import { ref } from 'vue';

const AT = '01-May-2020 05:18 pm';

export const items = ref([
  { id: 1,  code: '001', itemName: 'Masala Dosa',         category: 'Dosa',               restaurantPrice: 80,  barPrice: 80,  roomPrice: 90,  taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 2,  code: '002', itemName: 'Plain Dosa',           category: 'Dosa',               restaurantPrice: 60,  barPrice: 60,  roomPrice: 70,  taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 3,  code: '003', itemName: 'Chicken Biryani',      category: 'Briyani Chicken',    restaurantPrice: 180, barPrice: 190, roomPrice: 200, taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 4,  code: '004', itemName: 'Mutton Biryani',       category: 'Briyani Mutton',     restaurantPrice: 220, barPrice: 230, roomPrice: 250, taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 5,  code: '005', itemName: 'Veg Biryani',          category: 'Briyani Veg',        restaurantPrice: 140, barPrice: 140, roomPrice: 160, taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 6,  code: '006', itemName: 'Paneer Butter Masala', category: 'Curries',            restaurantPrice: 160, barPrice: 160, roomPrice: 180, taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 7,  code: '007', itemName: 'Butter Naan',          category: 'Breads at its best', restaurantPrice: 40,  barPrice: 40,  roomPrice: 50,  taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 8,  code: '008', itemName: 'Cold Coffee',          category: 'Cold Beverages',     restaurantPrice: 80,  barPrice: 90,  roomPrice: 100, taxType: 'Inclusive', tax: 'GST (12.00%)', state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 9,  code: '009', itemName: 'Masala Chai',          category: 'Hot Beverage',       restaurantPrice: 30,  barPrice: 30,  roomPrice: 40,  taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 10, code: '010', itemName: 'Gulab Jamun',          category: 'Desserts',           restaurantPrice: 60,  barPrice: 60,  roomPrice: 70,  taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'Off Sale', itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 11, code: '011', itemName: 'Veg Fried Rice',       category: 'Meals',              restaurantPrice: 120, barPrice: 120, roomPrice: 140, taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 12, code: '012', itemName: 'Chicken 65',           category: 'Starters',           restaurantPrice: 200, barPrice: 210, roomPrice: 220, taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 13, code: '013', itemName: 'Idly (2 pcs)',         category: 'Break Fast',         restaurantPrice: 40,  barPrice: 40,  roomPrice: 50,  taxType: 'Exclusive', tax: 'Tax Exempt',   state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 14, code: '014', itemName: 'Vada (2 pcs)',         category: 'Break Fast',         restaurantPrice: 40,  barPrice: 40,  roomPrice: 50,  taxType: 'Exclusive', tax: 'Tax Exempt',   state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
  { id: 15, code: '015', itemName: 'Puri Bhaji',           category: 'Break Fast',         restaurantPrice: 60,  barPrice: 60,  roomPrice: 70,  taxType: 'Exclusive', tax: 'GST (5.00%)',  state: 'On Sale',  itemType: 'Physical Item', note: '', imageUrl: '', lastAccessedBy: 'Administrator', lastAccessedAt: AT, createdAt: AT },
]);
